name: Sync Files
on:
  push:
    branches:
      - master  # 如果你的默认分支是 'main'，请替换为 main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          # 这行是关键，告诉同步Action给PR打上"automerge"标签
          PR_LABELS: automerge
